### ISSUE TITLE
Spike: Dynamic Models

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/spring2020-cs-gy-9223-frontend#21]
Research how to implement dynamic models in Django, so that we can build a new table for every sensor during runtime, without having to re-migrate. 

Relational approach
https://pypi.org/project/django-dynamic-model/

Non-relational approach
https://django-mongodb-engine.readthedocs.io/en/latest/

**Comment by Ray310** [comment]
Combining this with:
Knowledge Acquisition: Determine if existing Django module/library meets need to dynamically add / remove sensors #12
