### ISSUE TITLE
As <Sextant>, I want <to set up the repo> so that <we can start implementing our changes and testing them>.

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/spring2020-cs-gy-9223-frontend#22]
**User story**
As Sextant, I want to set up the repo so that we can start implementing our changes and testing them.
Set-up includes:
- creating the team repo, 
- travis (adding build badges for master/develop to repo), 
- coveralls (adding coverages badges for master/develop to repo),
- deploying to Heroku

**Acceptance criteria**

**Definition of Done**

**Comment by Ray310** [comment]
Completed
