### ISSUE TITLE
User Story: Export data in easy to use format

### ISSUE THREAD

**Issue by Ray310** [gcivil-nyu-org/spring2020-cs-gy-9223-frontend#35]
**User story**
As a user, I can export data in an easy to use format (like csv, json, etc.) so that I can store or analyze data outside of the application. 

**Acceptance criteria**

1. All events' data can be exported as one file
2. Data for any given event can be exported as a single file
3. Data for selected events can be exported as a single file or as a series of distinct files
4. Data is exported in an easy to use format

**Definition of Done**
Changes due to story:
1. Pass all automated and user testing at developer level
2. Are peer reviewed and merged into team (Sextants / Front-end) repository
3. Are deployed to (Sextants / Front-end) Heroku folder
4. Are peer reviewed and merged into class-level repository
5. Are successfully deployed to production code (Heroku)

**Comment by daisycrego** [comment]
transferred to class repo
