### ISSUE TITLE
Technical Story: Create Wireframe / Mockup of App Interface

### ISSUE THREAD

**Issue by Ray310** [gcivil-nyu-org/spring2020-cs-gy-9223-frontend#42]
**Technical story**
As a developer, I want to see what the app interface will look like so I can plan back-end functionality.

**Acceptance criteria**
1. Mock site is created that demonstrates proposed changes
2. Mock site is used to solicit feedback from front-end and back-end teams

**Definition of Done**
1. Mock site results in agreed upon site design

**Comment by ghost** [comment]
Wire frame was completed and it served its purpose.
